modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "latin_scriptor"
version = "${version}"
displayName = "Latin Scriptor"
authors = "Me!"
description = '''
This makes the spell components of Scriptor sound latin
'''
#logoFile = ""

[[dependencies.latin_scriptor]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.latin_scriptor]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.latin_scriptor]]
modId = "scriptor"
type = "required"
versionRange = "[1.3.5-1.21,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "latin_scriptor.mixins.json"
